BOT_TOKEN = "6034351669:AAHCHdiK2cdRqrsAzDsC1fJ1dKuTStvABbY"

# EXAMPLE: BOT_TOKEN = "5953961340:AAFiBeDXt7Yb10ShbV2O5z2oCzVTgjEK43g"

START_PIC = " "

# ENTER LINK OF PIC !

# FOR GETTING LINK, GO TO @Spl_Levi_Ackerman_Bot, SEND PIC AND REPLY /telegraph

SUPPORT_CHAT = " "

# ENTER USERNAME OF SUPPORT GROUP OR CHANNEL WITHOUT @

if SUPPORT_CHAT[0] == "@":
    SUPPORT_CHAT = SUPPORT_CHAT[1:]
